const LISTCONTACT = {
  LOADING: 'LISTPOKEMON_LOADING',
  FETCH_SUCCESS: 'LISTPOKEMON_FETCH_SUCCESS',
  FETCH_FAILED: 'LISTPOKEMON_FETCH_FAILED',
  UPDATE_SUCCESS: 'LISTPOKEMON_UPDATE_SUCCESS',
  UPDATE_FAILED: 'LISTPOKEMON_UPDATE_FAILED',
  DELETE_SUCCESS: 'LIST_POKEMON_DELETE_SUCCESS',
  DELETE_FAILED: 'LIST_POKEMON_DELETE_FAILED',
  ADD_SUCCESS: 'LIST_POKEMON_ADD_SUCCESS',
  ADD_FAILED: 'LIST_POKEMON_ADD_FAILED'
};

export { LISTCONTACT };
